### ISSUE TITLE
Ruby group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by anthonymr** [anthonymr/catalog-of-my-things#27]
Capstone Ruby project: https://github.com/anthonymr/catalog-of-my-things/

Project members: 3

Member distribution:

- Member 1: @anthonymr 
- Member 2: @RaphDasilva 
- Member 3: We split those issues between @anthonymr and @RaphDasilva until @AbdimulhinYussuf3675 shows up.

**Comment by Olamarx** [comment]
Hi Team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have a link to the kanban board you set up, kindly add a link to it directly.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by anthonymr** [comment]
Hi @Olamarx, We will do it. Thanks for your time.
